sudo: false

language: java

jdk: oraclejdk8

env: >
  METEOR_HOME=$HOME/.meteor
  JASMINE_BROWSER=Firefox

before_install:
  - "export PATH=$METEOR_HOME:$PATH"
  - "test -f $METEOR_HOME/meteor || curl https://install.meteor.com | sh"
  - "npm install eslint babel-eslint eslint-config-airbnb -g"
  - "npm install velocity-cli -g"

install:
  - "meteor update"

before_script:
  - "eslint $(pwd)"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "velocity test-app --ci"
  - "meteor run --production  > /dev/null 2>&1 &"

script:
  - "cd tests/e2e && mvn test"

before_cache:
  - "find $HOME/.m2 -name '*status.properties' -delete"

cache:
  directories:
  - "$HOME/.meteor"
  - "$HOME/.m2"

notifications:
  email: change
